# This is a basic workflow to help you get started with Actions

name: Sass Build

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [src-pages]
  pull_request:
    branches: [src-pages]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout source Git branch
      uses: actions/checkout@v2
      with:
        ref: src-pages

    - name: Make destination directory for compiled CSS
      run: mkdir -vp /tmp/tequendama/assets/css

    - name: Compile CSS from SCSS files
      uses: gha-utilities/sass-build@v0.2.2
      with:
        source: assets/css/styles.scss
        destination:  /tmp/tequendama/assets/css/styles.css

    - name: Upload Complied CSS
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Compiled-CSS
        path: /tmp/tequendama/assets/css/styles.css


