# This is a basic workflow to help you get started with Actions

name: Sass Build
uses: gha-utilities/sass-build@v0.2.2

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master, src-pages ]
  pull_request:
    branches: [ master, src-pages ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Make destination directory for compiled CSS
      run: mkdir -vp /tmp/tequendama/assets/css

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.2.2
        with:
          source: _scss/main.scss
          destination: /tmp/assets/css/main.css
          
    - name: Compile CSS from SCSS files
      uses: gha-utilities/sass-build@v0.2.2
        with:
          source: assets/css/styles.scss
          destination: /tmp/tequendama/assets/css/styles.css

    - name: Add and Commit changes to pr-pages branch
      run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add assets/css/*
          git commit -m 'Updates compiled CSS files'

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: pr-pages

    - name: Initialize Pull Request
      uses: gha-utilities/init-pull-request@v0.0.4
      with:
          pull_request_token: ${{ secrets.GITHUB_TOKEN }}
          head: pr-pages
          base: gh-pages
          title: 'Updates site files from latest Actions build'
          body: >
            Something similar to sass -t compressed assets/css/styles.scss 
            assets/css/styles.css
